### ISSUE TITLE
Call of not implemented method in FactorySwagger

### ISSUE THREAD

**Issue by corleonis** [nabbar/SwaggerValidator-PHP#18]
I was playing around with the library and found the following bug: https://github.com/njuhel/SwaggerValidator-PHP/blob/master/src/Common/FactorySwagger.php#L227

problem is there is no `init()` method on the base Exception class and that is throwing exception, I presume it just missed code after refactoring.

**Comment by nabbar** [comment]
Bug identify, will be fix on next release

**Comment by nabbar** [comment]
Fix in release 1.3.2
